### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by OBorovec** [phuijse/P4J#1]
Hi,  

I am trying to install your package on my win 10 laptop with Python 3.6. I have numpy and scipy installed but when installing `pip install P4J` via cmd, I am getting this response:
```
Exception:
Traceback (most recent call last):
  File "c:\programs\python\python36\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\programs\python\python36\lib\site-packages\pip\commands\install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "c:\programs\python\python36\lib\site-packages\pip\req\req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "c:\programs\python\python36\lib\site-packages\pip\req\req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "c:\programs\python\python36\lib\site-packages\pip\download.py", line 821, in unpack_url
    hashes=hashes
  File "c:\programs\python\python36\lib\site-packages\pip\download.py", line 663, in unpack_http_url
    unpack_file(from_path, location, content_type, link)
  File "c:\programs\python\python36\lib\site-packages\pip\utils\__init__.py", line 605, in unpack_file
    untar_file(filename, location)
  File "c:\programs\python\python36\lib\site-packages\pip\utils\__init__.py", line 577, in untar_file
    with open(path, 'wb') as destfp:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\borovec\\AppData\\Local\\Temp\\pip-build-r2jcs66h\\P4J\\P4J/aux.pyx'
``` 

I have a feeling, you have hardcoded path separator somewhere.

**Comment by phuijse** [comment]
Dear Ondrej

Thanks for your interest in my package. I'm getting a Windows machine so I
can reproduce this error and fix it.

In the meantime you may try installing by just cloning the repo and then

python setup.py install --user

Perhaps this way you won't encounter the error

Cheers

2017-07-22 8:26 GMT-04:00 Ondřej Borovec <notifications@github.com>:

**Comment by phuijse** [comment]
Dear Ondrej

I have refactored setup.py to take into account compilation of the C sources in MS Windows systems. I also updated the README with information regarding the compilers. 

I successfully installed the package on a Windows 8.1 system with MSVC 9.0 and python2.7 (conda). I tested both "pip install" and "setup.py install". 

Please tell me if you are able install the package on your system.

Cheers

**Comment by OBorovec** [comment]
Yes, the problem is resolved 👍 thanks you very much for quick response
